In [1]:
import numpy as np

In [9]:
import torch

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype='float32')

In [5]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype='float32')

In [10]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [13]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [15]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [17]:
w = torch.randn(2,3,requires_grad=True) #output x input
b = torch.randn(2, requires_grad=True) #out only

In [19]:
def model(x):
    return x @ w.t() + b

In [21]:
w,b

(tensor([[ 0.9786,  1.4911,  0.7817],
         [-0.0956, -0.4272, -0.5110]], requires_grad=True),
 tensor([ 0.4631, -0.4299], requires_grad=True))

In [23]:
preds = model(inputs)

In [25]:
preds

tensor([[205.4117, -58.0017],
        [270.7536, -79.4236],
        [330.7377, -95.6251],
        [193.3143, -47.4567],
        [265.8441, -83.8032]], grad_fn=<AddBackward0>)

In [27]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [29]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [31]:
loss = mse(preds, targets)

In [33]:
loss

tensor(30849.8535, grad_fn=<DivBackward0>)

In [35]:
loss.backward()

In [37]:
print(w)
print(w.grad)

tensor([[ 0.9786,  1.4911,  0.7817],
        [-0.0956, -0.4272, -0.5110]], requires_grad=True)
tensor([[ 15061.2217,  15616.2598,   9717.4863],
        [-13652.2119, -15637.9805,  -9526.5117]])


In [39]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [41]:
loss = mse(preds, targets)
print(loss)

tensor(30849.8535, grad_fn=<DivBackward0>)


In [43]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [45]:
preds = model(inputs)
print(preds)

tensor([[179.7738, -33.4601],
        [237.0846, -47.1400],
        [291.0707, -57.2658],
        [167.6396, -23.2807],
        [233.6562, -52.7005]], grad_fn=<AddBackward0>)


In [49]:
loss = mse(preds, targets)
print(loss)

tensor(20953.7988, grad_fn=<DivBackward0>)


In [51]:
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ 12415.9727,  12778.2539,   7965.2778],
        [-11116.4824, -12907.8164,  -7842.9165]])
tensor([ 322.6573, -299.6315])


In [53]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [56]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(14282.6846, grad_fn=<DivBackward0>)


In [58]:
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [60]:
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(169.4818, grad_fn=<DivBackward0>)
